
# ## ### ### # ## ### ## ### ### ### ###
# ## ### ### BUILT-IN LIBRARIES ### ###
# ## ### ### # ## ### ## ### ### ### ###
import logging

from deepface import DeepFace
import cv2

# ## ### ### ### ## ## ## ### ### ###
# ## ### ### CUSTOM LIBRARIES ### ###
# ## ### ### ### ## ## ## ### ### ###
import libs

from stdo import stdo
from tools import time_log, TIME_FLAGS, time_list
# from qt_tools import qtimer_Create_And_Run
from image_manipulation import draw_Rectangle, draw_Circle
from structure_ui import init_and_run_UI, Graphics_View  # , init_UI, Structure_UI
from structure_camera import CAMERA_FLAGS
from structure_ui_camera import Structure_Ui_Camera
from structure_threading import Thread_Object


# ## ### ### ### ### ## ## ## ### ### ### ### ###
# ## ### ### CAMERA UI CONFIGURATIONS ### ### ###
# ## ### ### ### ### ## ## ## ### ### ### ### ###


class Ui_Deep_Face(Structure_Ui_Camera):
    logger_level = logging.INFO
    # __Threads = dict()

    def __init__(self, *args, obj=None, logger_level=logging.INFO, **kwargs):
        super(Ui_Deep_Face, self).__init__(*args, **kwargs)

        # ## ### ### ### ###
        # ## Constructor ###
        # ## ### ### ### ###
        self.logger_level = logger_level
        self.__thread_Dict = dict()

        # ## ### ### ### ###
        # ## ### Init ### ##
        # ## ### ### ### ###
        self.init()

        self.configure_Button_Connections()
        self.configure_Other_Settings()
        self.init_QTimers()

        ###
        self.deep_Face_Process_Thread_Start(
            trigger_quit=self.is_Quit_App, trigger_pause=self.checkBox_Deep_Face_Active.isChecked)

    # ## ### ## ### ###
    # ## OVERWRITES ###
    # ## ### ## ### ###

    def init(self):
        """self.graphicsView_Camera.LCD_Number_List = [
            self.lcdNumber_Pointer_Color_Red,
            self.lcdNumber_Pointer_Color_Green,
            self.lcdNumber_Pointer_Color_Blue,
            self.lcdNumber_Pointer_Color_Grayscale,
            self.lcdNumber_Pointer_Color_Grayscale_Inverted
        ]"""
        self.configure_Other_Settings()
        # self.init_Buffers()
        # self.init_Threads()
        # self.connect_Threads()
        self.connect_to_Camera(
            CAMERA_FLAGS.CV2,
            0,
            self.spinBox_Buffer_Size.value(),
            self.exposure_Time
        )
        # """ #TODO
        self.graphicsView_Camera.init_Render_QTimer(
            connector_stream=self.camera_Instance.stream_Returner,
            delay=0.1
        )
        self.graphicsView_Camera_Deep_Face.init_Render_QTimer(
            connector_stream=self.stream_Flow,
            delay=0.01
        )

    def init_QTimers(self, *args, **kwargs):
        super(Ui_Deep_Face, self).init_QTimers(*args, **kwargs)

    '''
    This code is connecting the buttons to their respective functions The connect to
    Camera function connects the camera and starts streaming The remove the Camera function
    disconnects the camera and stops streaming The stream switch button changes between
    live video feed and buffer display of frames captured from the camera And finally
    when you click on clear buffer it clears all frames in memory for that particular
    instance of a camera object i e self
    - generated by stenography autopilot [ 🚗👩‍✈️ ]
    '''

    def configure_Button_Connections(self):
        self.pushButton_Connect_to_Camera.clicked.connect(
            lambda: self.connect_to_Camera(
                CAMERA_FLAGS.CV2,
                self.spinBox_Buffer_Size.value(),
                self.exposure_Time
            )
        )
        self.pushButton_Remove_the_Camera.clicked.connect(
            self.camera_Remove
        )
        self.pushButton_Stream_Switch.clicked.connect(
            self.stream_Switch
        )
        self.pushButton_Buffer_Clear.clicked.connect(
            lambda: None if self.camera_Instance is None
            else self.camera_Instance.buffer_Clear()
        )

    def configure_Other_Settings(self):

        # ## ### ## ###
        # ## BUFFER ###
        # ## ### ## ###
        self.horizontalSlider_Buffer_Step_Bar.setMinimum(0)
        self.spinBox_Buffer_Size.valueChanged.connect(
            lambda: (
                self.horizontalSlider_Buffer_Step_Bar.setMaximum(
                    self.spinBox_Buffer_Size.value()
                ),
                None if self.camera_Instance is None
                else self.camera_Instance.set_Buffer_Size(
                    self.spinBox_Buffer_Size.value()
                )
            )
        )

        self.horizontalSlider_Buffer_Step_Bar.valueChanged.connect(
            lambda: self.graphicsView_Renderer(
                self.graphicsView_Camera,
                None if self.camera_Instance is None else self.camera_Instance.get_Buffered_Image(
                    self.horizontalSlider_Buffer_Step_Bar.value()
                )
            )
        )

        self.checkBox_Deep_Face_Active.stateChanged.connect(
            self.checkbox_Action_Deep_Face
        )

    def closeEvent(self, *args, **kwargs):
        super(Ui_Deep_Face, self).closeEvent(*args, **kwargs)

        self.camera_Remove()

    # ## ### ## ### ###
    # ## ### ## ### ###
    # ## ### ## ### ###

    def stream_Flow(self):
        drawing_frame = None
        if self.camera_Instance is not None:
            current_frame = self.camera_Instance.stream_Returner()
            if current_frame is not None and self.checkBox_Deep_Face_Preprocess_Crop.isChecked() and (
                    self.spinBox_Crop_H.value() * 2 < current_frame.shape[0] and
                    self.spinBox_Crop_W.value() * 2 < current_frame.shape[1]) and (
                    self.spinBox_Crop_W.value() > 0 and self.spinBox_Crop_H.value() > 0
            ):
                start_point = [
                    self.spinBox_Crop_W.value(),
                    self.spinBox_Crop_H.value()
                ]
                end_point = [
                    current_frame.shape[1] - self.spinBox_Crop_W.value(),
                    current_frame.shape[0] - self.spinBox_Crop_H.value()
                ]
                # print(f"{start_point} | {end_point} ||| {current_frame.shape}")

                drawing_frame = current_frame.copy()
                draw_Rectangle(
                    drawing_frame,
                    start_point=start_point,
                    end_point=end_point,
                    color=(100, 155, 10),
                    thickness=2
                )
            else:
                drawing_frame = current_frame
        return drawing_frame

    '''
    This code is a thread that runs the deep face process The code will run in a loop
    until it receives quit signal from main program When the code gets pause signal
    it will wait for resume signal before continue running
    - generated by stenography autopilot [ 🚗👩‍✈️ ]
    '''

    def deep_Face_Process_Thread_Start(self, trigger_quit=None, trigger_pause=None):
        self.__thread_Dict["thread_deep_Face_Process"] = Thread_Object(
            name="System_Object.thread_print_info",
            delay=0.1,
            # logger_level=None,
            set_Daemon=True,
            run_number=None,
            quit_trigger=trigger_quit
        )
        self.__thread_Dict["thread_deep_Face_Process"].init(
            params=[trigger_pause],
            task=self.deep_Face_Process_Thread
        )
        self.__thread_Dict["thread_deep_Face_Process"].start()
        # pause_trigger = trigger_pause,

    def checkbox_Action_Deep_Face(self):
        if self.checkBox_Deep_Face_Active.isChecked():
            self.graphicsView_Camera.stop_Render_QTimer()
            self.graphicsView_Camera.init_Render_QTimer(
                connector_stream=lambda: self.__thread_Dict["thread_deep_Face_Process"].get_Result(),
                delay=1
            )
            # self.graphicsView_Camera_Deep_Face.stop_Render_QTimer()
            # self.graphicsView_Camera_Deep_Face.init_Render_QTimer(
            #     connector_stream=lambda: self.__thread_Dict["thread_deep_Face_Process"].get_Result(),
            #     delay=1
            # )
        else:
            if self.camera_Instance:
                self.graphicsView_Camera.stop_Render_QTimer()
                self.graphicsView_Camera.init_Render_QTimer(
                    connector_stream=self.camera_Instance.stream_Returner,
                    delay=1
                )
                # self.graphicsView_Camera_Deep_Face.stop_Render_QTimer()
                # self.graphicsView_Camera_Deep_Face.init_Render_QTimer(
                #     connector_stream=self.camera_Instance.stream_Returner,
                #     delay=1
                # )
            else:
                print("No Camera Connected")

    '''
    This code is a thread that runs in the background and processes images from the
    camera It takes an image preprocesses it crop resize then passes it to deep Face
    Process for processing The result of this process is returned as a dictionary with
    keys No Process Age Gender Race and Emotion These are all strings but can be converted
    into numbers using string methods such as int or float
    - generated by stenography autopilot [ 🚗👩‍✈️ ]
    '''

    def deep_Face_Process_Thread(self, trigger_pause):
        if self.camera_Instance is not None and trigger_pause():
            stream_image = self.camera_Instance.stream_Returner(
                auto_pop=False
            )
            if stream_image is not None:
                actions = [
                    self.checkBox_Deep_Face_Active_Age.text().lower()
                    if self.checkBox_Deep_Face_Active_Age.isChecked() else ""
                ] + [
                    self.checkBox_Deep_Face_Active_Gender.text().lower()
                    if self.checkBox_Deep_Face_Active_Gender.isChecked() else ""
                ] + [
                    self.checkBox_Deep_Face_Active_Race.text().lower()
                    if self.checkBox_Deep_Face_Active_Race.isChecked() else ""
                ] + [
                    self.checkBox_Deep_Face_Active_Emotion.text().lower()
                    if self.checkBox_Deep_Face_Active_Emotion.isChecked() else ""
                ]
                # stream_image = self.deep_Face_Process(stream_image)
                actions = [i for i in actions if i]

                time_log("deep_Face_Process_Preprocess", flag=TIME_FLAGS.START)
                # let's downscale the image using new  width and height
                if self.checkBox_Deep_Face_Preprocess_Crop.isChecked() and (
                    self.spinBox_Crop_H.value() * 2 < stream_image.shape[0]
                    and
                    self.spinBox_Crop_W.value() * 2 < stream_image.shape[1]
                ) and (
                    self.spinBox_Crop_W.value() > 0
                    and self.spinBox_Crop_H.value() > 0
                ):
                    stream_image = stream_image[
                        self.spinBox_Crop_H.value():-self.spinBox_Crop_H.value(),
                        self.spinBox_Crop_W.value():-self.spinBox_Crop_W.value(),
                        :
                    ]
                if self.checkBox_Deep_Face_Preprocess_Resize.isChecked() and (
                    self.spinBox_Resize_W.value() > 0
                    and self.spinBox_Resize_H.value() > 0
                ):
                    stream_image = cv2.resize(
                        stream_image,
                        (
                            self.spinBox_Resize_H.value(),
                            self.spinBox_Resize_W.value()
                        ),
                        interpolation=cv2.INTER_LINEAR
                    )
                time_log("deep_Face_Process_Preprocess", flag=TIME_FLAGS.END)

                time_log("deep_Face_Process", flag=TIME_FLAGS.START)
                if len(actions):
                    results, image_deep_face = self.deep_Face_Process(
                        image=stream_image,
                        actions=actions,
                        model_index=0
                    )
                else:
                    image_deep_face = stream_image
                    results = {"Is Process Active": "No"}
                time_log("deep_Face_Process", flag=TIME_FLAGS.END)

                dominant_emotion = ""
                dominant_gender = ""
                dominant_race = ""
                age = ""
                if type(results) is list and type(results[0]) is dict:
                    result = results[0]

                    if result.get("emotion"):
                        dominant_emotion = result.get("dominant_emotion", "")

                    if result.get("gender"):
                        dominant_gender = result.get("dominant_gender", "")

                    if result.get("race"):
                        dominant_race = result.get("dominant_race", "")

                    if result.get("age"):
                        age = result.get("age", "")

                    if result.get("region"):
                        roi = result["region"]
                        start_point = [roi["x"], roi["y"]]
                        end_point = [roi["w"], roi["h"]]
                        # end_point = [roi["x"] + roi["w"], roi["y"] + roi["h"]]
                        draw_Rectangle(
                            image_deep_face,
                            start_point=start_point,
                            end_point=end_point,
                            color=(0, 255, 0),
                            thickness=3
                        )
                        left_eye = roi.get("left_eye")
                        right_eye = roi.get("right_eye")
                        eye_radius = 5
                        if left_eye:
                            draw_Circle(
                                image_deep_face,
                                center_point=[
                                    left_eye[0],
                                    left_eye[1]
                                ],
                                radius=eye_radius,
                                color=(255, 0, 0),
                                thickness=3
                            )
                        if right_eye:
                            draw_Circle(
                                image_deep_face,
                                center_point=[
                                    right_eye[0],
                                    right_eye[1]
                                ],
                                radius=eye_radius,
                                color=(255, 0, 0),
                                thickness=3
                            )
                else:
                    result = results

                result_text = f"""
    |--[FPS Deep Face] {round(60 / (time_list['deep_Face_Process'][TIME_FLAGS.PASSED] + 0.000001), 2)} | ({round(time_list['deep_Face_Process'][TIME_FLAGS.PASSED], 2)} ms)
    |--[FPS Preprocess] {round(60 / (time_list['deep_Face_Process_Preprocess'][TIME_FLAGS.PASSED] + 0.000001), 2)} | ({round(time_list['deep_Face_Process_Preprocess'][TIME_FLAGS.PASSED], 2)} ms)
    |--[Image Shape] {image_deep_face.shape}
    |--[Result]
"""
                if len(actions):
                    result_text += f"""
    \\-- [Age] {age}
    \\-- [Dominant Emotion] {dominant_emotion}
    \\-- [Dominant Gender] {dominant_gender}
    \\-- [Dominant Race] {dominant_race}
"""

                self.QTFunction_Caller_Event_Add([
                    self.textEdit_Deep_Face_Results.setText,
                    [result_text]
                ])
                """ # OLD Feature of Stream. Currently graphicsView Class has its own streamer
                self.QTFunction_Caller_Event_Add([
                    self.graphicsView_Camera_Deep_Face.set_Background_Image,
                    [image_deep_face]
                ])
                """
                return image_deep_face  # , result

    '''
    This code is taking an image and returning a dictionary of the facial attributes
    The second thing it is doing is to take in a list of actions which are the keys
    for the dictionary that will be returned This code can also return multiple images
    at once if you pass in a list of images instead of just one The third thing it is
    doing is to use Deep Face\'s API to find faces in an image and then analyze them
    with Deep Face\'s API as well This last part isn\'t really necessary but was added
    because there were some issues with using Facenet or Openface on my computer so
    this seemed like a good way to get around those issues
    - generated by stenography autopilot [ 🚗👩‍✈️ ]
    '''

    def deep_Face_Process(self, image, actions=['age', 'gender', 'race', 'emotion'], model_index=0):
        # https://github.com/serengil/deepface

        # face verification
        """result = DeepFace.verify(img1_path="img1.jpg",
                                img2_path="img2.jpg", model_name=models[1])"""

        # face recognition
        """
        df = DeepFace.find(
            img_path="img1.jpg",
            db_path="C:/workspace/my_db",
            model_name=models[model_index]
        )
        """
        # df = DeepFace.find(img_path="img1.jpg", db_path="C:/workspace/my_db")

        # facial analysis
        # models = ["VGG-Face", "Facenet", "Facenet512",
        #           "OpenFace", "DeepFace", "DeepID", "ArcFace", "Dlib"]
        backends = ['opencv', 'ssd', 'dlib',
                    'mtcnn', 'retinaface', 'mediapipe']
        actions = [i for i in actions if i]
        # demography = DeepFace.analyze(img_path = "img4.jpg", detector_backend = backends[4])

        obj = dict()
        try:
            obj = DeepFace.analyze(
                img_path=image,
                actions=actions,  # ['emotion', 'facial expression'], #
                detector_backend=backends[2]
            )
            # stdo(1, obj, end='\r')
        except Exception as Error:
            stdo(3, f"Error: {Error}")  # , end='\r')
            obj = Error

        return obj, image


# ## ### ### ### ### ## ## ## ### ### ### ### ###
# ## ### ### ### ### ## ## ## ### ### ### ### ###
# ## ### ### ### ### ## ## ## ### ### ### ### ###

if __name__ == "__main__":
    # title, Class_UI, run=True, UI_File_Path= "test.ui", qss_File_Path = ""
    stdo(1, "Running {}...".format(__name__))
    app, ui = init_and_run_UI(
        "Deep Face Test",
        Ui_Deep_Face,
        UI_File_Path="deep_face_UI.ui"
    )
